
APP_CONST_C0001_RECIPE_TYPE = "C0001"
APP_CONST_C0002_UNIT_TYPE = "C0002"
APP_CONST_C0003_UNIT_POSITION_TYPE = "C0003"
APP_CONST_C0004_SALES_AREA_TYPE = "C0004"
APP_CONST_C0005_WEEKDAY_TYPE = "C0005"

USER_CONFIG_TYPE_START_WEEKDAY = "1"
USER_CONFIG_TYPE_TOWEEK_MENU_PLAN = "2"
USER_CONFIG_TYPE_CURRENT_GROUP = "3"
USER_CONFIG_TYPE_ACTIVATE_FLG = "4"
USER_CONFIG_TYPE_ACTIVATION_TOKEN = "5"

USER_CONFIG_TYPE_NM_START_WEEKDAY = "開始曜日"
USER_CONFIG_TYPE_NM_TOWEEK_MENU_PLAN = "選択中献立プランID"
USER_CONFIG_TYPE_NM_CURRENT_GROUP = "選択中グループID"
USER_CONFIG_TYPE_NM_ACTIVATE_FLG = "アクティベートフラグ"
USER_CONFIG_TYPE_NM_ACTIVATION_TOKEN = "アクティベーショントークン"

GROUP_CONFIG_TYPE_JOIN_FLG = "1"
GROUP_CONFIG_TYPE_INVITE_TOKEN = "5"

GROUP_CONFIG_TYPE_NM_JOIN_FLG = "参加フラグ"
GROUP_CONFIG_TYPE_NM_INVITE_TOKEN = "招待トークン"


ADMIN_USER_ID = 8

EMPTY_CD = "0"

TEST_USER_EMAILS = frozenset([
    "test@kondatemaker.invalid",
    "kondatemaker@test",
])